site_name: {{cookiecutter.project_name}}

# Page tree
nav:
  - Home:
        - Introduction: home/intro.md
  - Setup:
    - PIP: setup/pip_installation.md
  - Releases: home/intro.md
    - Changelog: releases/changelog.md

theme:
  name: material
  features:
      - navigation.tabs
      - content.code.annotate
      - content.tooltips
      - navigation.indexes
      - navigation.sections
      - navigation.tabs
      - navigation.top
      - navigation.tracking
      - search.highlight
      - search.share
      - search.suggest
      - toc.follow

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys

